### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by porsager** [Brouilles/bsdiff-node#16]
Hi there.. 

I noticed the `bsdiff-nodejs` npm package was deprecated, why is that?

I found that you've made some commits that point to `@brouilles/bsdiff-nodejs` instead, but that package does not exist, and isn't the name specified in package.json either?

Curious what the plan is ? 🙂

**Comment by Brouilles** [comment]
Hi,
I have lost my npm account. So it's why it's not up to date. Instead I have published the package on Github Package. It's more simple to publish and work fine.

**Comment by porsager** [comment]
Ah I see :) 

Not so easy if you're not set up with github packages, but I'll check it out ;)

I was confused because the readme says nothing about github packages but still shows the `npm install ...` command

Wrt. your npm account I think they could easily help you get it back.

**Comment by Brouilles** [comment]
My account have been deleted on npm. So maybe if the authoring account is deleted the package go to deprecated? I don't know.

**Comment by YuriArthas** [comment]
Hi, when I call "npm install @brouilles/bsdiff-nodejs@2.2.2", it report error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@brouilles%2fbsdiff-nodejs - Not found
npm ERR! 404
npm ERR! 404  '@brouilles/bsdiff-nodejs@2.2.2' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2020-10-30T03_52_36_775Z-debug.log
```

**Comment by Brouilles** [comment]
Hi @YuriArthas 
The package is not on the default npm repository. 
You need to setup Github Packages in your project. See https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#installing-a-package

**Comment by Brouilles** [comment]
Hi! 
I have listen to you. I have re-published the package on npmjs. So it's more simple for you to install!
See here https://www.npmjs.com/package/bsdiff-node

I needed to renamed it because the old name "bsdiff-nodejs" is locked (because I have in the past used it).
So `npm i bsdiff-node` :)

**Comment by porsager** [comment]
Very nice! Thank you
